@startuml
'https://plantuml.com/sequence-diagram

hide footbox

queue Events
queue Notifications
queue Commands
control Controller
participant Event

Events -> Controller: event
activate Controller
create Notification
Controller -> Notification: new
activate Notification
Notification -> Controller: item
deactivate Notification
Controller -> Notifications: send
deactivate Controller

Commands -> Controller: command
activate Controller
create Event
Controller -> Event: new
activate Event
Event -> Controller: item
deactivate Event
Controller -> Events: send
deactivate Controller


@enduml