@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

actor User
participant DetectingUserPresence as DUP
participant UserPresence as UP
participant UserPresenceDispatcher as UPD
participant UserPresenceEvent as UPE
queue Events

DUP -> User: is user here?
activate DUP
User -> DUP: user detected
create UP
DUP -> UP: new
DUP <- UP: instance
create UPD
DUP -> UPD: new
DUP -> UPD: notify
create UPE
UPD -> UPE: new
UPE -> UPD: instance
UPD -> Events: send






@enduml