@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

entity DF
control DetectionsObserver as DO
participant DetectionsDispatcher as DD
participant "DFS Event" as DFSE
queue Events

DF <- DO: any detections?
DF -> DO: detection
activate DO

create Detection
DO -> Detection : new
activate Detection
Detection --> DO : instance
deactivate Detection

DO -> DD: notify
deactivate DO

activate DD
create DFSE
DD -> DFSE : new
DFSE --> DD : instance
DD -> Events : send



@enduml