@startuml
'https://plantuml.com/sequence-diagram

hide footbox

queue Events
queue Notifications
control Controller
participant Event

Events -> Controller: event
activate Controller
create Notification
Controller -> Notification: new
activate Notification
Notification -> Controller: item
deactivate Notification
Controller -> Notifications: send
deactivate Controller

@enduml