@startmindmap
'https://plantuml.com/mindmap-diagram

!theme spacelab

title Motion Notifier

* <&star>Motion Notifier
** <&camera-slr>detections framework
*** <&warning> detections
**** <&folder>local
**** <&cloud>cloud
** <&clock>session
*** <&power-standby>on/off
** <&comment-square>client
*** commands
**** text
**** <&clock>time
*** <&envelope-closed>notifications
**** <&image>media
**** <&clock>time
** <&wrench>configurations
*** <&browser>interface
**** CLi
**** UI
*** <&file>files
** <&people>users
*** <&person>user
**** <&pulse>presence
***** <&wifi>network
***** <&eye>visual
** <&reload>agent
*** <&warning> detections
**** <&image>media
**** <&clock>time
*** commands
**** text
**** <&clock>time
** <&calendar>scheduler
legend right
  Short
  legend
endlegend
@endmindmap
