@startuml
'https://plantuml.com/component-diagram

left to right direction

package "Agent" {
    [Controller] as Agent_Controller
    package "Authentication" {
      [Presence Validator]
      [Network]
      [Visual]
    }

    package "Detections Framework Service" {
      () "Detections Framework" as DF
      [Controller] -> DF
      [Detection] <- [Controller]
    }


    package EventChannel {
      Agent_Controller --> [Event]
      [Presence Validator] -> [Event]
      [Detection] -> [Event]
    }

    package "Scheduling" {
      [Timer] -> [Event]
    }

}

package "Client" {
    [Controller] as Client_Controller
    [Messages Dispatcher] <-- Client_Controller

    package [Applications] {
    }
}

package MessagesChannel {
    [Command] <- [Message]
    [Message]
    [Message] -> [Notification]
}


cloud "Remote Clients" {
}

[Applications] <-- [Messages Dispatcher]
[Applications] -> "Remote Clients"
Client_Controller -> [Message]
Agent_Controller -> [Message]

[Controller] <-- Agent_Controller : commands
[Presence Validator] <-- Agent_Controller : commands
[Timer] <-- Agent_Controller : commands

[Presence Validator] -> [Network]
[Visual] <- [Presence Validator]

note right of "Remote Clients": CLi, WebUI, mobile
@enduml