@startuml
'https://plantuml.com/component-diagram

left to right direction

package "Agent" {
    [Controller] as Agent_Controller
    package "Authentication" {
      [Presence Validator]
      [Network]
      [Visual]
    }

    package "Detections Framework Controller" {
      [Detections Dispatcher] -> "Detections Framework"
    }

    node "Detections Framework" {
    }

    package "Scheduling" {
      [Timer]
    }
}


package "Client" {
    [Controller] as Client_Controller
    package Communicators {
        [Notifications Dispatcher]
        [Commands Receiver]
    }
    package Applications {
    }
}

package Configuration {
    [Configurations_Manager]
}

cloud "Remote Clients" {
}

[Applications] <-- [Notifications Dispatcher]
[Applications] <-- [Commands Receiver]
[Applications] -> [Configurations_Manager]
[Applications] --> "Remote Clients"
Client_Controller <- Agent_Controller
Client_Controller --> Agent_Controller
[Presence Validator] <-- Agent_Controller
[Configurations_Manager] <-- [Presence Validator]
[Timer] -> [Configurations_Manager]
[Detections Dispatcher] <-- Agent_Controller
[Configurations_Manager] <- [Detections Dispatcher]
[Timer] <-- Agent_Controller
Client_Controller -> [Commands Receiver]
[Notifications Dispatcher] <-- Client_Controller
[Presence Validator] -> [Network]
[Visual] <- [Presence Validator]

@enduml