@startuml
'https://plantuml.com/component-diagram

left to right direction

package "Agent" {
    [Controller] as Agent_Controller
    package "Authentication" {
      [Presence Validator]
      [Network]
      [Visual]
    }

    package "Detections Framework Controller" {
      [Detections Dispatcher] -> "Detections Framework"
      [Detection] <- [Detections Dispatcher]
      node "Detections Framework" {
      }
    }


    package EventChannel {
      Agent_Controller -> [Event]
      [Presence Validator] -> [Event]
      [Detections Dispatcher] -> [Event]
    }

    package "Scheduling" {
      [Timer] -> [Event]
    }

}

package Controller {

}

package "Client" {
    [Controller] as Client_Controller
    [Messages Dispatcher] <-- Client_Controller

    package [Applications] {
    }
}

package Messages {
    [Command] <- [Message]
    [Message]
    [Message] -> [Notification]
    [Controller] -> [Message]
}

package Configuration {
    [Configurations Manager]
}

cloud "Remote Clients" {
}

[Applications] <-- [Messages Dispatcher]
[Applications] -> [Configurations Manager]
[Applications] -> "Remote Clients"
Client_Controller -> [Message]
[Presence Validator] <- Agent_Controller
Agent_Controller -> [Message]
[Configurations Manager] <-- [Presence Validator]
[Timer] -> [Configurations Manager]
[Detections Dispatcher] <-- Agent_Controller
[Configurations Manager] <- [Detections Dispatcher]
[Timer] <-- Agent_Controller
[Presence Validator] -> [Network]
[Visual] <- [Presence Validator]
[Configurations Manager] <- [Controller]
[Controller] - UI

@enduml