@startuml
'https://plantuml.com/deployment-diagram



cloud App
actor User
package client


package agent {
  component Controller
  queue events as agent_events

  rectangle {
    component DFS
    component Auth
    component Scheduler
  }

  Auth <-> agent_events
  DFS <-> agent_events
  Scheduler <-down-> agent_events
  Controller <-down-> agent_events
}

package messages {
  queue commands
  queue notifications
}

User <-down-> App
App <-down-> client
client <-> commands
commands <-> Controller
Controller <-down-> notifications
client <-down-> notifications

@enduml