@startuml
'https://plantuml.com/class-diagram

abstract class User #palegreen ##[dashed]green {
 - name
}
class NetworkUser
class VisualUser


User <|-- NetworkUser
User <|-- VisualUser

class UserPresenceValidator {
   detectors: DetectingUserPresence[]
}

abstract class DetectingUserPresence #palegreen ##[dashed]green {
    users: User[]
    is_user_here(): UserPresence
}

interface Runnable #aliceblue ##[dotted]blue {
   start(): void
   stop(): void
}

interface UserPresenceDispatcher #aliceblue ##[dotted]blue {
  notify_about(presence: UserPresence)
}

class UserPresenceDispatcherViaQueue

class UserPresence {
  - user: User
  - data: PresenceData
}

abstract class PresenceData #palegreen ##[dashed]green {
}

 PresenceData <|-- NetworkPresence
 PresenceData <|-- VisualPresence

class DetectingViaNetwork
class DetectingVisual

DetectingUserPresence <|-- DetectingViaNetwork
DetectingUserPresence  <|-- DetectingVisual

UserPresenceDispatcher <|-down- UserPresenceDispatcherViaQueue

DetectingUserPresence "*" *.left "1" User


Runnable <|-- UserPresenceValidator


UserPresenceValidator "*" *.left. "1" DetectingUserPresence
UserPresence *. PresenceData
UserPresenceDispatcher o.. UserPresence
DetectingUserPresence o.. UserPresence

@enduml