@startuml
'https://plantuml.com/class-diagram



interface DetectionsFramework {
  exec_command(command: Commands)
  status(): Status
}

interface Detectable {
    detections(): Detection[]
}

class MotionFramework


package Detections {
    Interface Detection {
      time: number
      data: any
    }

    class MotionDetectionData {
       audio: string
       video: string
       image: string
    }

    class MotionDetection {
       time: number
       data: MotionDetectionData
    }

    class DetectionsDispatcher {
       notifyAbout(detection: Detection)
    }
}


enum Commands {
  START
  STOP
  RESTART
  TERMINATE
}

enum Status {
  STOPPED
  RUNNING
}

class DetectionsObserver {
   - framework: Detectable
   - eventsDispatcher: DetectionsDispatcher
   start(): void
   stop(): void
}


class Controller {
   - framework: DetectionsFramework
   - detectionsObserver: DetectionsObserver
}

DetectionsObserver o. Detectable
DetectionsDispatcher .* DetectionsObserver
DetectionsFramework <|-- MotionFramework
Detection <|-- MotionDetection
DetectionsFramework .. Status
Detectable .. Detection
DetectionsDispatcher .. Detection
DetectionsFramework .. Commands
MotionDetection .. MotionDetectionData
DetectionsObserver -down-* Controller
DetectionsFramework -down-* Controller
DetectionsFramework -up-|> Detectable

@enduml