@startuml
'https://plantuml.com/class-diagram



interface DetectionsFramework {
  detections(): Detection[]
  exec_command(command: Commands)
  status(): Status
}

class MotionFramework

Interface Detection {
  time: number
  data: any
}

class MotionDetectionData {
   audio: string
   video: string
   image: string
}

class MotionDetection {
   time: number
   data: MotionDetectionData
}

enum Commands {
  START
  STOP
  RESTART
  TERMINATE
}

enum Status {
  STOPPED
  RUNNING
}

class DetectionsObserver {
   - framework
   - eventsDispatcher
   start(): void
   stop(): void
}

class DetectionsDispatcher {
   notifyAbout(detection: Detection)
}

class Controller {
   - framework
   - detectionsObserver
}

DetectionsObserver o. DetectionsFramework
DetectionsDispatcher .* DetectionsObserver
DetectionsFramework <|-- MotionFramework
Detection <|-- MotionDetection
DetectionsFramework .. Status
DetectionsFramework .. Detection
DetectionsFramework .. Commands
MotionDetection .. MotionDetectionData
DetectionsObserver *- Controller
DetectionsFramework *- Controller

@enduml