@startuml
'https://plantuml.com/class-diagram

package Scheduler {

    class Controller {
       tasks: ScheduledTask[]
       exec(command: string)
       remove_task(task: ScheduledTask)
    }

    interface Runnable #aliceblue ##[dotted]blue {
       start(): void
       stop(): void
       is_running(): bool
    }

    Runnable <|-- Controller

    class ScheduledTask {
       controller: Controller
       scheduler: TimeScheduler
       get_execution_date(): Date
    }
    note left: at the end of the task\nremove the timer\nfrom controller

    package Commands {
        class CommandParser {
           parse(command: string): Command
        }

        class Command {
           do()
        }

        CommandParser o-> Command
    }
}


@enduml