@startuml
'https://plantuml.com/class-diagram

class Controller {
   schedulers: TaskScheduler[]
   exec(command: Command)
   removeTimer(timer: Timer)
}


interface Runnable #aliceblue ##[dotted]blue {
   start(): void
   stop(): void
   is_running(): bool
}

Runnable <|-- Controller

class TaskScheduler {
   controller: Controller
   at: date
   start(task: Task)
}
note left: at the end of the task\nremove the timer\nfrom controller


interface Executable #aliceblue ##[dotted]blue {
   exec()
}

class Command {
   do()
}

class ScheduledCommand {
}

Command <|--ScheduledCommand

@enduml