@startuml
'https://plantuml.com/object-diagram

package Events {
  object Event {
    id: long
    time_stamp: long
    from
    to
    state
  }

  object DFS {
    path: string
  }

  object Auth {
    presence: true/false
  }

  object Scheduler {
    detection: started/stopped
  }
}

DFS -up-|>Event
Auth -up-|>Event
Scheduler -up-|>Event

object London
object Washington
object Berlin
object NewYork

map CapitalCity {
 UK *-> London
 USA *--> Washington
 Germany *---> Berlin
}

NewYork --> CapitalCity::USA
@enduml
