@startuml

'https://plantuml.com/use-case-diagram

title Detections Framework

left to right direction

:System: as System
:Detections Framework: as Framework

rectangle configuration {
    (Configuration\nof shared resources paths) as (Conf)
    (Turning on/off the framework) as (On/Off)
    (Configuration of the framework run) as (Run)

    System -> (Connecting)
    Framework -- (Connecting)
    (Connecting) .> (Conf) : include
    (Connecting) .> (Run) : include
}

System -> (On/Off)
Framework -- (On/Off)

note right of (On/Off) : If it possible.

@enduml